print("Welcome to the Band Name Generator.")
print("What's the name of the city you grew up in?")
User_input = input()
print("What's your pet's name?")
UserPet_input = input()
print("Your band name could be " + User_input + " " + UserPet_input )
